os:
  - linux

dist:  bionic

language: php

php:
  - '7.3'

services:
  - docker

addons:
  hosts:
    - tabrasa8.ifdev

env:
  - COMPOSER_MEMORY_LIMIT=-1

git:
  # Do a full clone
  depth: false
  # Avoid logging git clone messages
  quiet: true

notifications:
  email:
    - lisa@ifsight.com
  on_success: change
  on_failure: always

before_install:
  - export PATH=$PATH:$HOME/.local/bin
  - sudo apt-get -qq update
  - sudo apt-get install -y pv
  # Removing AWS CLI install for now, may need later
  #- curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  #- unzip awscli-bundle.zip
  #- ./awscli-bundle/install -b ~/bin/aws
  #- rm -Rf awscli-bundle.zip
  #- rm -Rf awscli-bundle
  # Adding bin path to global path to support post-composer build process and finding binaries for testing purposes
  - export PATH=~/bin:$PATH
  - mkdir -p ~/shared
  - docker-compose pull

before_script:
  # initial composer build process
  - composer install
  - curl https://git.drupalcode.org/project/drupal/-/raw/8.8.x/sites/default/default.settings.php -o ./docroot/sites/default/default.settings.php
  - docker-compose up -d --build
  - docker-compose ps
  - sudo chmod a+w docroot/sites/default/files
  - sleep 15
  - chmod 0777 ./docroot/sites/default/settings.php
  - docker-compose exec php7.3 /bin/sh -c "cd /var/www/html/docroot; ../bin/drush site:install --db-url=mysql://drupal:drupal@db/drupal --account-name='admin' --account-pass='admin' --account-mail='ifdrupaladmin@ifsight.net' --site-name='Tabula Rasa 8' --site-mail='ifdrupaladmin@ifsight.net' -y"
  # Copying our specific settings.php over the one created by drush site:install so that our settings.local.php file gets loaded when site is bootstrapped
  - chmod 0777 ./docroot/sites/default/settings.php
  - cp ./drupal/settings.php ./docroot/sites/default/settings.php
  - chmod 0644 ./docroot/sites/default/settings.php
  - chmod 0777 ./docroot/sites/default/settings.local.php
  - cp ./drupal/settings.travis.php ./docroot/sites/default/settings.local.php
  # Run a cache reset on the drupal install
  - docker-compose exec php7.3 /bin/sh -c "cd /var/www/html/docroot; ../bin/drush cr"

script:
  - ./scripts/test.sh

