os:
  - linux

dist:  bionic

language: php
php:
  - '7.3'

jobs:
  include:
    - name: TabRasa8 Test Run 1
      script:
        - echo "Test Run 1 - Address, Admin Toolbar, AdvAgg, Allowed Formats, Audit Files, Better Exposed Filters, Block Field, Captcha, Cloudflare, Components!, Config Filter, Config Ignore, Config Split, CTools, Date Popup, Devel, Diff, Eash Breadcrumb, Elasticsearch Connector, Embed"
        - ./scripts/test1.sh
    - name: TabRasa8 Test Run 2
      script:
        - echo "Test Run 2 - Entity, Entity Browser, Entity Embed, Entity Reference Revisions, Environment Indicator, External Links, Field Group, File Entity, FontAwesome, Fulcrum Whitelist (skipped), Geocoder, Geolocation, Google Analytics, IF Helper, Inline Entity Form, Libraries API, LinkIt, MailSystem, Masquerade, Menu Block"
        - ./scripts/test2.sh
    - name: TabRasa8 Test Run 3
      script:
        - echo "Test Run 3 - Metatag, Paragraphs, PathAuto, Plupload, Purge, Purge Queuer URL, RECaptcha, Redirect, Redis, Scheduler, Search API, Search API Autocomplete, Simple Sitemap, SMTP, Social Media Links, Token, Twig Tweak, Typed Data, Ultimate Cron, Varnish Purge"
        - ./scripts/test3.sh
    - name: TabRasa8 Test Run 4
      script:
        - echo "Test Run 4 - IF Varnish Purge Tags, Views Reference, Webform, Youtube"
        - ./scripts/test4.sh
    - name: HCPL Test Run 5
      script:
        - echo "Test Run 5 - Add to Calendar, Context, CSV Serialization, External Authentication, Facets, Flag, Full Calendar View, Gather Content, HTML Formatter, Media Entity Image, Migrate Plus, Migrate Source CSV, Migrate Tools, Office Hours, Queue UI, RRSSB, Search API Fast, Search API SOLR, Single DateTime, Video Embed Field, Views Autocomplete Filters, Views Data Export"
        - ./scripts/test5.sh
    - name: BCPL Test Run 6
      script:
        - echo "Test Run 6 - Ajax View Demo, Courier, Date Recur, Dynamic Entity Reference, Editor File, Entity Clone, Entity Reference View Select, Group, Google Translate, Insert, Permissions by Term, RNG, RNG Contact, RNG Quick, TAC Lite, Unlimited Number, Views Entity Operations Access (VEOA), Views Advanced Routing"
        - ./scripts/test6.sh
    - name: BWSC Test Run 7
      script:
        - echo "Test Run 7 - Better Social Sharing Buttons, Block Exclude Pages, Content Moderation Notifications, DropzoneJS, Elasticsearch Connector Autocomplete, Entity Update, Geofield, Media Bulk Upload, Media Entity Actions, Menu Item Extras, Quick Node Clone, Sitemap, Twitter Block, Views Infinite Scroll"
        - ./scripts/test7.sh
    - name: COBB Test Run 8
      script:
        - echo "Test Run 8 - Add To Any, Date Recur Interactive, Menu Trail buy Path, Optional dend DAte, Permissions Filters, S3FS, S3FS Cors Scheduler Content Moderation Integration, Selective Bettere Exposed Filters, Siteimprove, Twig Field Value, User Default Page, Views Taxonomy Term Name Depth"
        - ./scripts/test8.sh

    - name: CDPU-CPP Test Run 18
      script:
        - echo "Test Run 18 - Block Class, CKEditor Table Tools Toolbar, CKEditor Video Detector, Display Suite, Easy Install"
        - ./scripts/test18.sh
services:
  - docker

addons:
  hosts:
    - tabrasa8.ifdev

env:
  - COMPOSER_MEMORY_LIMIT=-1

git:
  # Do a full clone
  depth: false
  # Avoid logging git clone messages
  quiet: true

notifications:
  email:
    - lisa@ifsight.com
    - jacqui@ifsight.com
  on_success: change
  on_failure: always

before_install:
  - export PATH=$PATH:$HOME/.local/bin
  - sudo apt-get -qq update
  - sudo apt-get install -y pv
  # Removing AWS CLI install for now, may need later
  #- curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  #- unzip awscli-bundle.zip
  #- ./awscli-bundle/install -b ~/bin/aws
  #- rm -Rf awscli-bundle.zip
  #- rm -Rf awscli-bundle
  # Adding bin path to global path to support post-composer build process and finding binaries for testing purposes
  - export PATH=~/bin:$PATH
  - mkdir -p ~/shared
  - docker-compose pull

before_script:
  # initial composer build process
  - if [ -n "$GITHUB_COMPOSER_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_COMPOSER_TOKEN}; fi;
  # Configures composer to discard changes when "recloning" a submodule repository, usually happens when applying patches
  - composer config discard-changes true
  - composer install
  - curl https://git.drupalcode.org/project/drupal/-/raw/8.8.x/sites/default/default.settings.php -o ./docroot/sites/default/default.settings.php
  - docker-compose up -d --build
  - docker-compose ps
  - sudo chmod a+w docroot/sites/default/files
  - sleep 15
  - chmod 0777 ./docroot/sites/default/settings.php
  - docker-compose exec php7.3 /bin/sh -c "cd /var/www/html/docroot; ../bin/drush site:install --db-url=mysql://drupal:drupal@db/drupal --account-name='admin' --account-pass='admin' --account-mail='ifdrupaladmin@ifsight.net' --site-name='Tabula Rasa 8' --site-mail='ifdrupaladmin@ifsight.net' -y"
  # Copying our specific settings.php over the one created by drush site:install so that our settings.local.php file gets loaded when site is bootstrapped
  - chmod 0777 ./docroot/sites/default/settings.php
  - cp ./drupal/settings.php ./docroot/sites/default/settings.php
  - chmod 0644 ./docroot/sites/default/settings.php
  - chmod 0777 ./docroot/sites/default/settings.local.php
  - cp ./drupal/settings.travis.php ./docroot/sites/default/settings.local.php
  # Second compoesr install to re-install modules removed due to patching during installation of "require-dev" modules
  - composer install
  # Run a cache reset on the drupal install
  - docker-compose exec php7.3 /bin/sh -c "cd /var/www/html/docroot; ../bin/drush cr"
