version: '3.7'

services:
  nginx:
    hostname: drupal.local
    image: fulcrum/nginx:1.16
    volumes:
      - ./datamounts/nginx/etc/nginx:/etc/nginx
      - ./:/var/www/html:ro
    ports:
      - 80:80
    environment:
      TZ: EST5EDT
      fulcrum_webroot: docroot
    depends_on:
      - php7.3
      - db

  php7.3:
    image: codementality/php7.3-drush10
    volumes:
      - ./datamounts/php/etc/php7.3:/etc/php7:ro
      - ./datamounts/php/etc/fulcrum/php/fulcrum.php:/fulcrum.php:ro
      - ./datamounts/php/etc/fulcrum/php/fulcrum.php:/fulcrum/fulcrum.php:ro
      - ./:/var/www/html
    ports:
      - "9073"
    environment:
      TZ: 'EST5EDT'
      COMPOSER_MEMORY_LIMIT: -1
    depends_on:
      - db

  db:
    image: fulcrum/mariadb:latest
    volumes:
     - ./datamounts/mysql/etc/mysql:/etc/mysql:ro
     - dbdata:/var/lib/mysql
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
       - searchdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  selenium:
    image: selenium/standalone-chrome:3.14.0
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - nginx
      - php7.3

volumes:
  dbdata:
    driver: local
  searchdata:
    driver: local
